import { Injectable } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { Hotel } from './entities/hotel.entity';

@Injectable()
export class HotelsRepository {
        private readonly hotels: Hotel[] = [
    {
      id: 'goa-hotel-1',
      partnerId: 'hotel-partner-goa',
      name: 'Taj Exotica Resort & Spa',
      city: 'Goa',
      location: 'Central Goa',
      description: 'Experience the ultimate luxury at Taj Exotica Resort & Spa located in Goa.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 296,
      taxesAndFees: 53,
      totalRooms: 56,
      availableRooms: 56,
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'goa-hotel-2',
      partnerId: 'hotel-partner-goa',
      name: 'The Leela Goa',
      city: 'Goa',
      location: 'Central Goa',
      description: 'Experience the ultimate luxury at The Leela Goa located in Goa.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 212,
      taxesAndFees: 58,
      totalRooms: 22,
      availableRooms: 38,
      image: 'https://images.unsplash.com/photo-1522792850028-9a6401a6b4af?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'goa-hotel-3',
      partnerId: 'hotel-partner-goa',
      name: 'W Goa',
      city: 'Goa',
      location: 'Central Goa',
      description: 'Experience the ultimate luxury at W Goa located in Goa.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 595,
      taxesAndFees: 31,
      totalRooms: 39,
      availableRooms: 22,
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'goa-hotel-4',
      partnerId: 'hotel-partner-goa',
      name: 'ITC Grand Goa Resort',
      city: 'Goa',
      location: 'Central Goa',
      description: 'Experience the ultimate luxury at ITC Grand Goa Resort located in Goa.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 489,
      taxesAndFees: 60,
      totalRooms: 46,
      availableRooms: 10,
      image: 'https://images.unsplash.com/photo-1551882547-ff40c0d129df?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'goa-hotel-5',
      partnerId: 'hotel-partner-goa',
      name: 'Taj Fort Aguada Resort',
      city: 'Goa',
      location: 'Central Goa',
      description: 'Experience the ultimate luxury at Taj Fort Aguada Resort located in Goa.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 364,
      taxesAndFees: 50,
      totalRooms: 11,
      availableRooms: 26,
      image: 'https://images.unsplash.com/photo-1542314831-c6a4d142104d?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'jaipur-hotel-1',
      partnerId: 'hotel-partner-jaipur',
      name: 'Rambagh Palace',
      city: 'Jaipur',
      location: 'Central Jaipur',
      description: 'Experience the ultimate luxury at Rambagh Palace located in Jaipur.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 155,
      taxesAndFees: 69,
      totalRooms: 45,
      availableRooms: 15,
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'jaipur-hotel-2',
      partnerId: 'hotel-partner-jaipur',
      name: 'The Oberoi Rajvilas',
      city: 'Jaipur',
      location: 'Central Jaipur',
      description: 'Experience the ultimate luxury at The Oberoi Rajvilas located in Jaipur.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 499,
      taxesAndFees: 58,
      totalRooms: 45,
      availableRooms: 21,
      image: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'jaipur-hotel-3',
      partnerId: 'hotel-partner-jaipur',
      name: 'Taj Jai Mahal Palace',
      city: 'Jaipur',
      location: 'Central Jaipur',
      description: 'Experience the ultimate luxury at Taj Jai Mahal Palace located in Jaipur.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 183,
      taxesAndFees: 43,
      totalRooms: 55,
      availableRooms: 44,
      image: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'jaipur-hotel-4',
      partnerId: 'hotel-partner-jaipur',
      name: 'Fairmont Jaipur',
      city: 'Jaipur',
      location: 'Central Jaipur',
      description: 'Experience the ultimate luxury at Fairmont Jaipur located in Jaipur.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 245,
      taxesAndFees: 52,
      totalRooms: 53,
      availableRooms: 59,
      image: 'https://images.unsplash.com/photo-1590874103328-eaac2cb9e532?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'jaipur-hotel-5',
      partnerId: 'hotel-partner-jaipur',
      name: 'ITC Rajputana',
      city: 'Jaipur',
      location: 'Central Jaipur',
      description: 'Experience the ultimate luxury at ITC Rajputana located in Jaipur.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 181,
      taxesAndFees: 44,
      totalRooms: 22,
      availableRooms: 50,
      image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'mumbai-hotel-1',
      partnerId: 'hotel-partner-mumbai',
      name: 'The Taj Mahal Palace',
      city: 'Mumbai',
      location: 'Central Mumbai',
      description: 'Experience the ultimate luxury at The Taj Mahal Palace located in Mumbai.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 330,
      taxesAndFees: 53,
      totalRooms: 45,
      availableRooms: 12,
      image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'mumbai-hotel-2',
      partnerId: 'hotel-partner-mumbai',
      name: 'The Oberoi Mumbai',
      city: 'Mumbai',
      location: 'Central Mumbai',
      description: 'Experience the ultimate luxury at The Oberoi Mumbai located in Mumbai.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 322,
      taxesAndFees: 45,
      totalRooms: 33,
      availableRooms: 23,
      image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ec8fa62?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'mumbai-hotel-3',
      partnerId: 'hotel-partner-mumbai',
      name: 'Trident Nariman Point',
      city: 'Mumbai',
      location: 'Central Mumbai',
      description: 'Experience the ultimate luxury at Trident Nariman Point located in Mumbai.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 127,
      taxesAndFees: 23,
      totalRooms: 26,
      availableRooms: 23,
      image: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'mumbai-hotel-4',
      partnerId: 'hotel-partner-mumbai',
      name: 'ITC Maratha',
      city: 'Mumbai',
      location: 'Central Mumbai',
      description: 'Experience the ultimate luxury at ITC Maratha located in Mumbai.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 176,
      taxesAndFees: 30,
      totalRooms: 22,
      availableRooms: 21,
      image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'mumbai-hotel-5',
      partnerId: 'hotel-partner-mumbai',
      name: 'Taj Lands End',
      city: 'Mumbai',
      location: 'Central Mumbai',
      description: 'Experience the ultimate luxury at Taj Lands End located in Mumbai.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 387,
      taxesAndFees: 34,
      totalRooms: 43,
      availableRooms: 54,
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'delhi-hotel-1',
      partnerId: 'hotel-partner-delhi',
      name: 'The Leela Palace',
      city: 'Delhi',
      location: 'Central Delhi',
      description: 'Experience the ultimate luxury at The Leela Palace located in Delhi.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 509,
      taxesAndFees: 22,
      totalRooms: 46,
      availableRooms: 43,
      image: 'https://images.unsplash.com/photo-1566665797719-1d0a58fa4922?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'delhi-hotel-2',
      partnerId: 'hotel-partner-delhi',
      name: 'Taj Palace',
      city: 'Delhi',
      location: 'Central Delhi',
      description: 'Experience the ultimate luxury at Taj Palace located in Delhi.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 552,
      taxesAndFees: 66,
      totalRooms: 57,
      availableRooms: 26,
      image: 'https://images.unsplash.com/photo-1598928506311-c55dbf682855?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'delhi-hotel-3',
      partnerId: 'hotel-partner-delhi',
      name: 'ITC Maurya',
      city: 'Delhi',
      location: 'Central Delhi',
      description: 'Experience the ultimate luxury at ITC Maurya located in Delhi.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 283,
      taxesAndFees: 36,
      totalRooms: 13,
      availableRooms: 36,
      image: 'https://images.unsplash.com/photo-1560067174-e553b3647603?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'delhi-hotel-4',
      partnerId: 'hotel-partner-delhi',
      name: 'The Oberoi New Delhi',
      city: 'Delhi',
      location: 'Central Delhi',
      description: 'Experience the ultimate luxury at The Oberoi New Delhi located in Delhi.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 592,
      taxesAndFees: 57,
      totalRooms: 34,
      availableRooms: 49,
      image: 'https://images.unsplash.com/photo-1550581190-e221371089a8?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'delhi-hotel-5',
      partnerId: 'hotel-partner-delhi',
      name: 'The Imperial',
      city: 'Delhi',
      location: 'Central Delhi',
      description: 'Experience the ultimate luxury at The Imperial located in Delhi.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 167,
      taxesAndFees: 35,
      totalRooms: 10,
      availableRooms: 15,
      image: 'https://images.unsplash.com/photo-1618773928120-22c7a523b092?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'kerala-hotel-1',
      partnerId: 'hotel-partner-kerala',
      name: 'Taj Kumarakom Resort',
      city: 'Kerala',
      location: 'Central Kerala',
      description: 'Experience the ultimate luxury at Taj Kumarakom Resort located in Kerala.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 426,
      taxesAndFees: 21,
      totalRooms: 56,
      availableRooms: 15,
      image: 'https://images.unsplash.com/photo-1615880480556-9764a7541ef0?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'kerala-hotel-2',
      partnerId: 'hotel-partner-kerala',
      name: 'The Zuri Kumarakom',
      city: 'Kerala',
      location: 'Central Kerala',
      description: 'Experience the ultimate luxury at The Zuri Kumarakom located in Kerala.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 597,
      taxesAndFees: 51,
      totalRooms: 55,
      availableRooms: 51,
      image: 'https://images.unsplash.com/photo-1578683014746-98477141f237?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'kerala-hotel-3',
      partnerId: 'hotel-partner-kerala',
      name: 'Taj Bekal Resort',
      city: 'Kerala',
      location: 'Central Kerala',
      description: 'Experience the ultimate luxury at Taj Bekal Resort located in Kerala.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 592,
      taxesAndFees: 58,
      totalRooms: 37,
      availableRooms: 10,
      image: 'https://images.unsplash.com/photo-1580828368523-263a4369e853?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'kerala-hotel-4',
      partnerId: 'hotel-partner-kerala',
      name: 'Niraamaya Retreats',
      city: 'Kerala',
      location: 'Central Kerala',
      description: 'Experience the ultimate luxury at Niraamaya Retreats located in Kerala.',
      stars: 4,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 379,
      taxesAndFees: 39,
      totalRooms: 45,
      availableRooms: 14,
      image: 'https://images.unsplash.com/photo-1582610116311-6b8f38f7158f?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    },
    {
      id: 'kerala-hotel-5',
      partnerId: 'hotel-partner-kerala',
      name: 'Spice Village Thekkady',
      city: 'Kerala',
      location: 'Central Kerala',
      description: 'Experience the ultimate luxury at Spice Village Thekkady located in Kerala.',
      stars: 5,
      rating: 0,
      reviewCount: 0,
      pricePerNight: 347,
      taxesAndFees: 35,
      totalRooms: 42,
      availableRooms: 41,
      image: 'https://images.unsplash.com/photo-1595521624992-48a59aef95e3?auto=format&fit=crop&q=80&w=800',
      amenities: ['Free WiFi', 'Pool', 'Restaurant', 'Gym'].slice(0, Math.floor(Math.random() * 3) + 2),
      status: 'active',
      createdAt: new Date(),
    }
  ];

  create(
    partnerId: string,
    data: Omit<Hotel, 'id' | 'partnerId' | 'createdAt' | 'availableRooms'> & {
      id?: string;
      availableRooms?: number;
    },
  ): Hotel {
    const hotel: Hotel = {
      id: data.id || randomUUID(),
      partnerId,
      name: data.name,
      city: data.city,
      location: data.location,
      description: data.description,
      stars: data.stars,
      rating: data.rating,
      reviewCount: data.reviewCount,
      pricePerNight: data.pricePerNight,
      taxesAndFees: data.taxesAndFees,
      totalRooms: data.totalRooms,
      availableRooms: data.availableRooms ?? data.totalRooms,
      image: data.image,
      amenities: data.amenities,
      status: data.status,
      createdAt: new Date(),
    };

    this.hotels.push(hotel);
    return { ...hotel, amenities: [...hotel.amenities] };
  }

  findAll(filters?: { location?: string }): Hotel[] {
    const location = filters?.location?.trim().toLowerCase();
    return this.hotels
      .filter((hotel) => hotel.status === 'active')
      .filter((hotel) => {
        if (!location) return true;
        return (
          hotel.location.toLowerCase().includes(location) ||
          hotel.city.toLowerCase().includes(location)
        );
      })
      .map((hotel) => ({ ...hotel, amenities: [...hotel.amenities] }));
  }

  findById(id: string): Hotel | undefined {
    const hotel = this.hotels.find((item) => item.id === id);
    return hotel ? { ...hotel, amenities: [...hotel.amenities] } : undefined;
  }

  findByPartnerId(partnerId: string): Hotel[] {
    return this.hotels
      .filter((hotel) => hotel.partnerId === partnerId)
      .map((hotel) => ({ ...hotel, amenities: [...hotel.amenities] }));
  }

  update(id: string, data: Partial<Hotel>): Hotel | undefined {
    const index = this.hotels.findIndex((hotel) => hotel.id === id);
    if (index === -1) return undefined;

    this.hotels[index] = {
      ...this.hotels[index],
      ...data,
      amenities: data.amenities ?? this.hotels[index].amenities,
    };

    return {
      ...this.hotels[index],
      amenities: [...this.hotels[index].amenities],
    };
  }

  delete(id: string): boolean {
    const index = this.hotels.findIndex((hotel) => hotel.id === id);
    if (index === -1) return false;
    this.hotels.splice(index, 1);
    return true;
  }
}
