export const tour = [
  {
    id: "001",
    guideId: "10001",
    title: "Versailles Palace Tour",
    customerId: "20001",
    customer: "Emma Thompson",
    email: "emma@email.com",
    phone: "+33 6 12 34 56 78",
    destination: "Versailles, France",
    location: "Versailles, France",
    plan_iternary: ["Main Gates", "Hall of Mirrors", "King's Grand Apartments", "The Gardens"],
    currentloction: null,
    dateTime: "2026-03-30 | 09:00 AM",
    status: "pending", 
    guests: 3,
    amount: 360,
    duration: "4 hours"
  },
  {
    id: "002",
    guideId: "10001",
    title: "Latin Quarter Food Tour",
    customerId: "20002",
    customer: "Robert Martinez",
    email: "robert@email.com",
    phone: "+33 6 98 76 54 32",
    destination: "Paris, France",
    location: "Paris, France",
    plan_iternary: ["St Michel Fountain", "Rue de la Huchette", "Pantheon"],
    currentloction: null,
    dateTime: "2026-04-05 | 11:00 AM",
    status: "pending",
    guests: 2,
    amount: 240,
    duration: "3 hours"
  },
  {
    id: "003",
    guideId: "10002",
    title: "Pondicherry Cycle Tour",
    customerId: "20001",
    customer: "Anjali Sharma",
    email: "anjali@xploreo.com",
    phone: "+91 91234 56780",
    destination: "French Quarter Cycle Tour",
    location: "Pondicherry, India",
    plan_iternary: ["Rock Beach", "French Colony", "Auroville"],
    currentloction: null,
    dateTime: "2026-04-01 | 07:00 AM",
    status: "pending",
    guests: 1,
    amount: 500,
    duration: "3 hours"
  },
  {
    id: "004",
    guideId: "10001",
    title: "Seine River Evening Cruise",
    customerId: "20002",
    customer: "John Williams",
    email: "john@email.com",
    phone: "+33 6 11 22 33 44",
    destination: "Paris, France",
    location: "Paris, France",
    plan_iternary: ["Eiffel Tower Dock", "Louvre Pass", "Notre-Dame Pass", "Trip Completion"],
    currentloction: "Trip Completion",
    dateTime: "2026-03-24 | 08:00 PM",
    status: "completed",
    guests: 6,
    amount: 540,
    duration: "2.5 hours",
    rating: 5,
    review: "Absolutely wonderful experience! The guide was knowledgeable and friendly."
  },
  {
    id: "005",
    guideId: "10001",
    title: "Montmartre Walking Tour",
    customerId: "20001",
    customer: "Lisa Anderson",
    email: "lisa@email.com",
    phone: "+33 6 55 66 77 88",
    destination: "Montmartre, Paris",
    location: "Paris, France",
    plan_iternary: ["Moulin Rouge", "Cafe des Deux Moulins", "Place du Tertre", "Sacré-Cœur Basilica", "Trip Completion"],
    currentloction: "Place du Tertre",
    dateTime: "2026-03-30 | 02:00 PM",
    status: "ongoing",
    guests: 4,
    amount: 320,
    duration: "3 hours"
  },
  {
    id: "006",
    guideId: "10001",
    title: "Notre-Dame & Sainte-Chapelle Tour",
    customerId: "20002",
    customer: "Maria Garcia",
    email: "maria@email.com",
    phone: "+33 6 88 99 00 11",
    destination: "Ile de la Cite, Paris",
    location: "Paris, France",
    plan_iternary: ["Pont Neuf", "Sainte-Chapelle", "Notre-Dame Cathedral", "Trip Completion"],
    currentloction: "Trip Completion",
    dateTime: "2026-03-23 | 10:00 AM",
    status: "completed",
    guests: 2,
    amount: 200,
    duration: "2 hours",
    rating: 5,
    review: "Beautiful tour with great historical insights!"
  },
  {
    id: "48291",
    guideId: "10001",
    title: "Kyoto Cultural Escape",
    customerId: "20001",
    customer: "Anjali Sharma",
    email: "anjali@xploreo.com",
    phone: "+91 91234 56780",
    destination: "Kyoto, Japan",
    location: "Kyoto, Japan",
    plan_iternary: ["Fushimi Inari shrine walk", "Tea ceremony in Gion", "Historic district food trail", "Trip Completion"],
    currentloction: "Tea ceremony in Gion",
    dateTime: "2026-10-12 | 09:00 AM",
    status: "ongoing",
    guests: 2,
    amount: 502000,
    duration: "5 days",
    itinerary: [
      { day: "Day 1", title: "Arrival", detail: "Check-in at Ritz-Carlton Kyoto." },
      { day: "Day 2", title: "Fushimi Inari", detail: "Morning shrine visit." }
    ],
    paymentBreakdown: { flights: 142000, stay: 210000, activities: 98000, guide: 52000 },
    documents: [{ id: "doc-flight", title: "Flight Ticket", status: "Ready" }]
  },
  {
    id: "39210",
    guideId: "10001",
    title: "Santorini Sunset Retreat",
    customerId: "20001",
    customer: "Anjali Sharma",
    email: "anjali@xploreo.com",
    phone: "+91 91234 56780",
    destination: "Santorini, Greece",
    location: "Santorini, Greece",
    plan_iternary: ["Oia sunset cruise", "Winery tasting", "Island photography walk", "Trip Completion"],
    currentloction: null,
    dateTime: "2026-07-04 | 11:00 AM",
    status: "pending",
    guests: 2,
    amount: 345000,
    duration: "7 days",
    itinerary: [
      { day: "Day 1", title: "Arrival", detail: "Check-in at Caldera Horizon Suites." }
    ],
    paymentBreakdown: { flights: 110000, stay: 145000, activities: 56000, guide: 34000 },
    documents: [{ id: "doc-hotel-2", title: "Hotel Voucher", status: "Ready" }]
  }
];